# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
    
pool:
  vmImage: 'ubuntu-latest'

variables:
  system.debug: false

steps:

 - task: DotNetCoreCLI@2
   inputs:
     command: 'build'
     arguments: '-c release'
     projects: '**/*.csproj'
   name: 'build_backend'

 - task: NodeTool@0
   inputs:    
      versionSpec: '10.x'
      
 - script:
    npm install @angular/cli@8.3.14
   workingDirectory: 'UI/bcs-frontend'
   name: 'install_angular'
   displayName: 'install Angular'

 - script:  
        npm install
   workingDirectory: 'UI/bcs-frontend'
   name: 'install_npm'
   displayName: 'install dependencies via npm'

 - script: |
        echo NG VERSION:
        npm run ng --version
        npm uninstall @angular-devkit/build-angular
        npm install @angular-devkit/build-angular
        npm uninstall typescript
        npm install typescript@3.5.1
        echo NG VERSION AFTER UPDATE:
        npm run ng --version
   workingDirectory: 'UI/bcs-frontend'
   name: 'install_correct_ts'
   displayName: 'use correct angular-devkit and TS'

 - script:  
      npx ng build --prod    
   workingDirectory: 'UI/bcs-frontend'
   name: 'build_ui'
   displayName: 'ng build'

 - task: CopyFiles@2
   inputs:
    SourceFolder: 'BCS/API/bin/release/netcoreapp3.0'
    Contents: '**'
    TargetFolder: 'UI/bcs-frontend/dist/backend'
    OverWrite: true
   name: 'copy_backend_to_frontend'
   displayName: 'copy backend'

 - task: PublishBuildArtifacts@1
   inputs:
    PathtoPublish: 'UI/bcs-frontend/dist'
    ArtifactName: 'app'
    publishLocation: 'Container'
