# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
    
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
  displayName: 'Run a multi-line script'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'UI/bcs-frontend'

#- task: CmdLine@2
#  inputs:
#    script: |
#      echo yolo
#      npm install
#      echo done
#    workingDirectory: 'UI/bcs-frontend'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'UI/bcs-frontend'
    customCommand: 'install @angular/cli'


- task: CmdLine@2 
  inputs:
      script: |
        ng --version
        echo ng --version
        
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'UI/bcs-frontend'
    customCommand: 'run build'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'app'
    publishLocation: 'Container'
    
#- task: CmdLine@2
#  inputs:
#    script: |
#      echo install complete...now build the app
#      ng build
#      echo done
#    workingDirectory: 'UI/bcs-frontend'